function MatWrapper(varargin)
% Wrapper for the nw model 
[fldr, contrast, muE, muI, inputTStart, inputTStop, inputStepSize] ...
    = DefaultArgs(varargin, {'~/Documents/cnrs/code/network_model/', [0.25 : 0.25 : 1], 0.1, 0.1, 0, 0, 0});
%    for kcontr = 1 : length(contrast)
            system(['./mysolver ', ...
                    num2str(0), ' ', ...
                    num2str(0.25), ' ', ...
                    num2str(muE), ' ', ...
                    num2str(muI), ' ', ...
                    num2str(inputTStart), ' ', ...
                    num2str(inputTStop), ' ', ...
                    num2str(inputStepSize)]);
            
            
            %   end
            %end
end